# Generated by Django 5.0.6 on 2024-07-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0002_alter_coaches_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images')),
                ('coach_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.coaches')),
            ],
        ),
    ]
