# Generated by Django 5.0.6 on 2024-07-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0003_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
